apiVersion: v1
kind: PersistentVolume
metadata:
  name:  nfs-pv
spec:
  volumeMode: Filesystem
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    path: /nfs/pv
    server: 192.168.152.220