apiVersion: v1
kind: PersistentVolumeClaim         
metadata:
  name: nfs-pvc
spec:
  volumeMode: Filesystem         
  accessModes:                   
    - ReadWriteMany             
  resources:
    requests:
      storage: 10Gi            