---
apiVersion: v1
kind: PersistentVolume          # 声明持久卷
metadata:
  name:  nfs-pv
spec:
  volumeMode: Filesystem        
  capacity:
    storage: 10Gi              
  accessModes:                 
  - ReadWriteMany              
  persistentVolumeReclaimPolicy: Retain    
  nfs:
    path: /path/to/nfs/share
    server: nfs-server-ip