apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-sc-example
spec:
  selector:
    matchLabels:
      app: nginx-sc
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-sc
    spec:
      volumes:
      - name: scm-pvc                 # 给资源起名在volumeMount中引用
        persistentVolumeClaim:          # 指定使用PVC持久卷
          claimName: scm-pvc            # PVC资源名称
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - protocol: TCP
          containerPort: 80
        volumeMounts:
        - name: scm-pvc                        # volumes定义的资源名称
          mountPath: /usr/share/nginx/html/        # mount持久卷的路径
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-sc-service
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: nginx-sc
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sc-nginx-ing
  #annotations:
  #  kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
  - host: "test-sc.bar.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            #name: nginx-web-svc
            name: nginx-sc-service
            port:
              number: 80
